name: Deploy to Portainer

on:
  push:
    branch:
      - 'testing'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USER }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpoint-id: 2
          stack-name: 'test-version'
          stack-definition: 'docker-compose.yml'
